### ISSUE TITLE
MySensors

### ISSUE THREAD

**Issue by flatsiedatsie** [nRFMesh/nRF52_Mesh#6]
Are you aware of the MySensors project? It seems that you are re-creating it.

**Comment by wassfila** [comment]
Yes, aware of it, recreating it is a matter of definition. I have an account at MySensors and started considering it more seriously towards the mid of my gen 2 (STM32), now I'm at gen 4 (Zigbee).
MySensors have the same scope as I do, a custom mesh protocol, but that's about it. Some serious companies do have custom mesh protocols (e.g. Wirepas). I was never a fan of Arduino and prefer the suppliers SDK's for more flexibility and better understanding. I also like to rewrite things for pedagogical reasons, I rewrote lots of I²C SPI drivers for STM8 for example that already existed. The HW is not my field so wanted to try my own low power PCB design for fun.
The same statement could be mentioned for MySensors as they're recreating the Zigbee which is even a standard, why not simply run zigbee on arduino, well obviously for complexity reasons which is now changing little by little. HomeSmartMesh is more an open investigation project and a feasibility check.
Currently, I started using all kinds of Zigbee sensors and they're integrated in the same framework as my custom sensors, through Python, into influxDB then Grafana, thanks to the deCONZ ConBee Zigbee dongle that offers websocket API.
So gen3 was the nRF52 with still custom protocol, gen4 switched to the nRF52840 that supports both Zigbee and Thread and is mixed with off the shelf products.
Now that Zigbee is more popular in the future I will focus more on the Raspberry pi server programming and the famous ESP32 with full fledged MQTT Json OTA,... and still there without arduino rather the bare ESP-IDF from espressif.

**Comment by flatsiedatsie** [comment]
Great. Just wanted to make sure :-)

**Comment by wassfila** [comment]
Yeah, thanks for the reminder anyway, I went there again and I see an active discussion around the nRF52840 which I'll be using as well : https://forum.mysensors.org/topic/9717/everything-nrf52840
Struggle between closed source standards implementations and open source projects, we're all in the same boat. I'll definitely keep checking MySensors evolution and side by side comparision with the Open Thread options.
