### ISSUE TITLE
Design files ... Motion_tag ?

### ISSUE THREAD

**Issue by RandoSY** [nRFMesh/nRF52_Mesh#7]
Are they available?

Thanks!

Randy

**Comment by wassfila** [comment]
Yes, they're here in this repo : https://github.com/nRFMesh/nRF52_Mesh/tree/master/boards/nrf52_sensortag/pcb

Actually the motion tag is a different firmware application reusing the same PCB, the design from the beginning planned to have two soldering options :

- Sensortag : soldering two I²C sensors
- Motion tag : soldering the MPU6050 sensor

see photo

![20190403_190903](https://user-images.githubusercontent.com/1510763/55498808-c8509580-5644-11e9-8db5-d7ab973a7762.jpg)

**Comment by RandoSY** [comment]
Thank you! ☺
--
Sent from myMail for Android Wednesday, 03 April 2019, 01:15PM -04:00 from Wassim  notifications@github.com :
